# This is a basic workflow to help you get started with Actions
name: deploy-to-host

# Controls when the workflow will run
on: 
  release:
    types:
      - "published"

jobs:
  deploy:
    name: Push to hemisphere
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'placeholder'
          
      - name: Adding known hosts
        run: |
          echo $PWD
          echo $whoami
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          
      - name: Deploy with rsync to '/var/www/' on hemisphere
        run:
          ls -lha
          rsync -avz $GITHUB_WORKSPACE ${{ secrets.SSH_USER }}@${{secrets.SSH_HOST }}:${{secrets.DIRECTORY }}