name: run-dds-to-png

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Push to hemisphere
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'placeholder'
          
      - name: Adding known hosts
        run: |
          echo $PWD
          echo $whoami
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          
      - name: Deploy with rsync to '/var/www/' on hemisphere
        run: |
          echo $GITHUB_WORKSPACE
          ls -lha
          rsync -avz $GITHUB_WORKSPACE ${{ secrets.SSH_USER }}@${{secrets.SSH_HOST }}:/var/www/tech-tree.contrastellar.com/public_html