name: run-dds-to-png

on:
  workflow_dispatch:

jobs:
  convert:
    name: Convert given dds folder to png.
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'placeholder'

      - name: install fish
        run: |
          sudo apt-get install fish --yes

      - name: load into fish
        run: |
          fish
          echo $PWD
          echo $SHELL

      - name: install python and wand
        run: |
          sudo apt-get install python3 --yes
          sudo apt-get install libmagickwand-dev --yes

      - name: install packages with pip
        run: (which python3) -m pip install -r ./assets/py/requirements.txt